pki_path                      = "HYOK-Wrapper"
pki_max_lease_ttl_seconds     = 315360000 # 10 years
pki_default_lease_ttl_seconds = 157680000 # 5 years
pki_root_cert_ttl             = 157680000 # 5 years
pki_root_cn                   = "Root CA"
pki_role_allowed_domains      = ["hyok.vt.ch"]
pki_role_allow_subdomains     = true
approle_role_name             = "hyok"
transit_key_name              = "salesforce"
transit_exportable            = true